### ISSUE TITLE
when reloading results page crashes

### ISSUE THREAD

**Issue by danielLutziger** [sopra-fs23-group-13/meme-it-client#151]

**Comment by danielLutziger** [comment]
chat object is assigned wrongly

**Comment by danielLutziger** [comment]
memes are not correctly displayed, there are background colors and stuff. this is essential as sometimes the fonts are not readable.

**Comment by danielLutziger** [comment]
meme of the game is not always loaded (e.g. first meme was the best one, meme is always loading and not displaying)

**Comment by danielLutziger** [comment]
styling in page width not correct

**Comment by pablotanner** [comment]
> meme of the game is not always loaded (e.g. first meme was the best one, meme is always loading and not displaying)

This was caused by a backend issue and is fixed if you use server branch 181.

And I thought the box background was just for the meme creation, is that supposed to be visible during the leaderboard too? I think it would be smart to use actual text borders instead of boxes, pretty sure this would make text visible on any background without blocking the meme.
